trigger:
- main  # Change this to your default branch

pool:
  vmImage: 'ubuntu-latest'  # You can use other images as well

steps:
- task: MavenAuthenticate@0
  inputs:
    mavenServiceConnection: 'your-service-connection-name'  # Optional, if you need to authenticate to a Maven repository

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml file
    goals: 'clean install'  # Maven goals you want to run
    options: '-X -DskipTests=true'  # Combine additional Maven options here
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'  # Specify the JDK version you need
    mavenVersionOption: 'Default'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/*.xml'  # Path to your test results
    codeCoverageToolOption: 'None'  # Change if you are using a coverage tool